### ISSUE TITLE
Can't get GANSynth to work with GPU. CUBLAS_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by megacorvega** [magenta/magenta#1763]
Here's the code snippet ignoring all the deprecation warnings above. This also includes

https://pastebin.com/e566fAe2

`(0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`

Any ideas?

**Comment by megacorvega** [comment]
I think I fixed it?? Just added this in `gansynth_generate.py`

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
